### ISSUE TITLE
Doesn't work with custom user

### ISSUE THREAD

**Issue by AKurmazov** [KoalixSwitzerland/koalixcrm#113]
ERRORS:
accounting.Booking.lastmodifiedby: (fields.E301) Field defines a relation with the model 'auth.User', which has been swapped out.
        HINT: Update the relation to point at 'settings.AUTH_USER_MODEL'.
accounting.Booking.staff: (fields.E301) Field defines a relation with the model 'auth.User', which has been swapped out.
        HINT: Update the relation to point at 'settings.AUTH_USER_MODEL'.
crm.Contact.lastmodifiedby: (fields.E301) Field defines a relation with the model 'auth.User', which has been swapped out.
        HINT: Update the relation to point at 'settings.AUTH_USER_MODEL'.
crm.Contract.lastmodifiedby: (fields.E301) Field defines a relation with the model 'auth.User', which has been swapped out.
        HINT: Update the relation to point at 'settings.AUTH_USER_MODEL'.

and so on

**Comment by scaphilo** [comment]
Thank you for the reported issues and the hints, i will try to reproduce as soon as possible

**Comment by scaphilo** [comment]
@AKurmazov 
Is it correct that you tried to use the koalixcrm togehter with https://github.com/jcugat/django-custom-user?
I would accept a pull request from your side to enable the this support.
But as it has no obvious features from me - I would not personally spend time from this implementation.

Other useres please feel free to vote for the implementation of this feature by marking it with the smily

**Comment by scaphilo** [comment]
Other github- users please feel free to vote for the implementation of this feature by marking it with the smily

**Comment by AKurmazov** [comment]
@scaphilo I don't use django-custom-user. Just re-defined the User model and the UserManager
