### ISSUE TITLE
Manage dependencies versions with pip-compile-multi

### ISSUE THREAD

**Issue by peterdemin** [KoalixSwitzerland/koalixcrm#117]
Hi, would you like to use [pip-compile-multi](https://github.com/peterdemin/pip-compile-multi) for dependencies versions management (lock and upgrade)?
If so, I'd be happy to contribute it.

**Comment by scaphilo** [comment]
Hi Peter, thanks for bringing upt the point. I will need to study your documentation again.
But i looks interesting. As soon as i had some time to discuss this with @Hacont we can decide.
