### ISSUE TITLE
Docker improvements

### ISSUE THREAD

**Issue by bahron83** [KoalixSwitzerland/koalixcrm#150]
I think that Docker files could be changed to pursue the following improvements.

For development: use of a volume for the code, to avoid container restart after every change in the code

For production: use of a webserver (Nginx) to contain the Django application and let the user browse the site via standard ports 80 (http) and 443 (https)

**Comment by bahron83** [comment]
I've been already using configurations like above on my fork (see branch jlscom). I could prepare a pull request if it's fine with you.

**Comment by scaphilo** [comment]
@Hacont: do you agree with the suggested approach? i especially like that the restart is not required after a code change

**Comment by Hacont** [comment]
@bahron83 : Thanks for the offer to prepare a pull request to improve our Docker build. I think this will be a very useful improvement to this project. Please send us your Pull request and we will merge the changes to our master.
