### ISSUE TITLE
Automated pypi package generation

### ISSUE THREAD

**Issue by scaphilo** [KoalixSwitzerland/koalixcrm#193]
**Context**
To minimize the required effort for deployment on pypi, every new version which is committed to the master shall automatically become a new pypi package with version increase.
Every commit to the development branch shall also result in a new pypi package also with a new version but with the suffix V1.12**dev....**

**Idea**
This issue is about the whole development process in this open source project:
The release should work like this:

***Versioning***
Vaa.bb_ccc1
aa: Major version increase. A Major version increase must happen when a new "version development branch" is opened. 
bb: Minor version in increase. A Minor version increase happens whenever a specific version is already on the master and need so be updated because of security fix or equivalent that cannot wait for a new merge from a version development branch.
cccc: A new developement version increase happens whenever a pull request is merged into the version development branch

A new version development branch can only be opened by the repo master, the repo master must make sure that the version development branch is equipped with proper restrictions and checks to ensure that pypi packages are created only for the new version not accidentially for an existing major version.

***Version development branch***
1. Developers work on their feature branch which is built and tested with every commit/push to the origin.
2. When the developer has finished the development on this feature branch he needs to make a pull request towards the development branch.
3. On this pull request an additional testcase is executed which makes sure that only commits with a version increase in the version.py file can be merged
4. The pull request is accepted and the new pypi package is pushed and the development branch is automatically tagged with this version

[koalixcrm_backend_versioning.svg](https://github.com/scaphilo/koalixcrm/blob/feature/AddIllustrationsToProjectReport_Issue236/documentation/source/images/koalixcrm_backend_versioning.svg)

**Comment by Geektrovert** [comment]
Hey, can I work on this? I'm still new to this so some guidance would really help!

**Comment by scaphilo** [comment]
Ah yes of cause I would by very interesting to work with you. I will try to add some more details to the issue so that it is easier for you to start. You can also get in contact with me via email: aaron.riedener@gmail.com
