### ISSUE TITLE
Integration with oscar & oscar-accounts ?

### ISSUE THREAD

**Issue by goutnet** [KoalixSwitzerland/koalixcrm#266]
Would it be possible to integrate with oscar-accounts for the accounts providing?

oscar-accounts provides a bit more features (and plays well with oscar as well)…

it could be either replace the Account model with the oscar-accounts or attach an oscar-account reference to it… 

would you accept a pull request that would go in this direction?

**Comment by scaphilo** [comment]
It looks quite promising. I will need to think about your proposal in more detail. I will come back to you once I have a clearer picture.

**Comment by goutnet** [comment]
I am waiting for an answer on their issue tracker before getting serious here:

https://github.com/django-oscar/django-oscar-accounts/issues/64

Depending on their response, the way I saw it would be to use model inheritance to use Oscar-accounts as base class:

https://github.com/django-oscar/django-oscar-accounts/issues/64

This would ensure koalix to be independent in the way it manages extra fields (ex: account documentation etc..)
