### ISSUE TITLE
nested accounts

### ISSUE THREAD

**Issue by goutnet** [KoalixSwitzerland/koalixcrm#267]
It would be nice if we could have nested accounts on Koalix, would you accept pull request in this direction?

**Comment by scaphilo** [comment]
This for sure! I remember an other user who has requested this sort of feature as well.

**Comment by goutnet** [comment]
I have started to look how the system is setup, the more I look at it, the more I think oscar-accounts would be a better fit (even though they don't, yet, have nested accounts),  as oscar-accounts is really more targetted toward finance management, works in multiple currencies, and is generally well proven.

I made a request from Oscar-Account team if they would accept it, I would add this to their lib first then integrate into Koalix

https://github.com/django-oscar/django-oscar-accounts/issues/64
