### ISSUE TITLE
Dockerfile is not Correctly Configured

### ISSUE THREAD

**Issue by pushpendrahpx** [KoalixSwitzerland/koalixcrm#327]
**Describe the bug**
Dockerfile is not correctly configured, running command  " docker-compose up " results in error

So Should I Proceed with it to Correctly Configured ?

Thank You !

**Comment by 868jjm** [comment]
Did you ever get the project to work?

**Comment by goetzk** [comment]
There is a large rework to docker in the development branch; I don't know what @scaphilo 's plans are regarding making a release from it but you might have some luck running that instead of master.

**Comment by scaphilo** [comment]
Hello @goetzk, @868jjm,  @pushpendrahpx i will build the docker image with integrated koalixcrm and docker images in the next few days. I decide to separate the repositories with the docker container creation for production:
https://github.com/KoalixSwitzerland/koalixcrm-prod-container
and the one for the development:
https://github.com/KoalixSwitzerland/koalixcrm-dev-container
